FROM node:22-bookworm

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm install

ENV NODE_ENV=production
ENV PORT=3000
ENV BASE_PATH=/

RUN pnpm --filter @workspace/web run build

EXPOSE 3000

CMD ["pnpm","--filter","@workspace/web","run","serve"]

