FROM node:22-bookworm

WORKDIR /app

RUN corepack enable

COPY . .

RUN pnpm install

ENV NODE_ENV=production
ENV PORT=3001

RUN pnpm --filter @workspace/api-server run build

EXPOSE 3001

CMD ["pnpm","--filter","@workspace/api-server","run","start"]

