import { eq } from "drizzle-orm";
import { db, pool, productsTable } from "@workspace/db";
import type { InsertProduct } from "@workspace/db";

/* ─── Seed data ──────────────────────────────────────────── */

const products: InsertProduct[] = [
  /* ══ رستوران سنتی کولی (b001) ═══════════════════════════ */
  {
    slug: "abgoosht-mazandaran",
    name: "آبگوشت دیزی مازندرانی",
    description:
      "آبگوشت اصیل مازندرانی با گوشت گوسفندی تازه، نخود و سیب‌زمینی. پخته‌شده با دستور سنتی خانواده‌های شمالی، سرو با نان تازه محلی و دوغ کوهی.",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "غذای اصیل",
    price: 89_000,
    originalPrice: 110_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 124,
    coverGradient: "linear-gradient(135deg, #C2410C 0%, #7C2D12 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    phone: "011-44567890",
    whatsapp: "09111234567",
    city: "ساری",
    tags: ["آبگوشت", "غذای سنتی", "مازندران", "شمال"],
    benefits: [
      "گوشت گوسفندی تازه روزانه",
      "بدون مواد نگهدارنده",
      "دستور پخت اصیل مازندرانی",
      "سرو با نان تازه محلی",
    ],
    faqs: [
      { question: "آیا امکان تحویل درب منزل وجود دارد؟", answer: "بله، سفارش آنلاین با تحویل در محدوده شهر ساری قبول می‌شود." },
      { question: "آیا مواد اولیه حلال هستند؟", answer: "بله، تمامی مواد اولیه حلال و دارای مجوز بهداشت هستند." },
    ],
    terms: "لطفاً پیش از سفارش با رستوران تماس بگیرید. سفارش‌های بالای ۱۰ نفر نیاز به هماهنگی قبلی دارند.",
    expiresAt: new Date("2026-08-31T23:59:59Z"),
    socialProof: { purchases: 248, views: 1240, saves: 87 },
    ratingBreakdown: [
      { label: "کیفیت غذا", score: 4.9 },
      { label: "تازگی مواد", score: 4.8 },
    ],
    ratingDistribution: [
      { star: 5, count: 89, percent: 72 },
      { star: 4, count: 22, percent: 18 },
      { star: 3, count: 8, percent: 6 },
      { star: 2, count: 3, percent: 2 },
      { star: 1, count: 2, percent: 2 },
    ],
    reviews: [
      {
        id: "r1",
        userName: "سارا م.",
        date: "2026-03-15",
        rating: 5,
        text: "واقعاً خوشمزه‌ترین آبگوشتی بود که خورده‌ام! اصیل و طعم واقعی شمال داشت.",
        pros: ["طعم عالی", "گوشت نرم"],
        helpful: 12,
      },
      {
        id: "r2",
        userName: "رضا ک.",
        date: "2026-02-28",
        rating: 5,
        text: "دستور پخت سنتی رعایت شده، نان محلی هم همراه داشت.",
        pros: ["اصالت طعم"],
        helpful: 8,
      },
    ],
  },

  {
    slug: "mahi-shekampor",
    name: "ماهی شکم‌پر دریای خزر",
    description:
      "ماهی تازه خزر با پرکردن سبزی‌های بومی — رازیانه، گشنیز، تره‌فرنگی — و ادویه‌های محلی. کباب‌شده روی آتش ذغال.",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "دریایی",
    price: 145_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 89,
    coverGradient: "linear-gradient(135deg, #0369A1 0%, #082F49 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    phone: "011-44567890",
    whatsapp: "09111234567",
    city: "ساری",
    tags: ["ماهی", "غذای دریایی", "خزر", "کباب"],
    benefits: ["ماهی تازه صید روز از خزر", "بدون رنگ و مواد نگهدارنده", "پخت سنتی روی آتش ذغال"],
    socialProof: { purchases: 312, views: 1560, saves: 105 },
  },

  {
    slug: "morgh-torsh-gilani",
    name: "مرغ ترش گیلانی",
    description:
      "خورشت مرغ ترش گیلانی با آلوچه محلی، گردو و رب انار. یکی از مشهورترین غذاهای اصیل استان گیلان.",
    businessId: "b002",
    businessName: "خانه‌غذای گیلانه",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "خورشت",
    price: 115_000,
    originalPrice: 140_000,
    discountPercent: 18,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 67,
    coverGradient: "linear-gradient(135deg, #4D7C0F 0%, #1A2E05 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    city: "رشت",
    tags: ["مرغ ترش", "گیلان", "رب انار"],
    socialProof: { purchases: 189, views: 945, saves: 63 },
  },

  {
    slug: "bamiyeh-ba-asal",
    name: "بامیه با عسل طبیعی",
    description:
      "بامیه خانگی با روغن نباتی و آرد گندم سبوس‌دار، همراه با عسل طبیعی کوهستان البرز.",
    businessId: "b003",
    businessName: "شیرینی‌پزی مادربزرگ",
    businessVerified: false,
    category: "شیرینی و دسر",
    subcategory: "شیرینی",
    price: 65_000,
    currency: "تومان",
    rating: 4.5,
    reviewCount: 42,
    coverGradient: "linear-gradient(135deg, #B45309 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "آمل",
    tags: ["بامیه", "شیرینی", "عسل"],
  },

  {
    slug: "abrisham-rasht-1m",
    name: "پارچه ابریشم رشت (۱ متر)",
    description:
      "پارچه ابریشم خالص دستباف از کارگاه‌های سنتی رشت. رنگ‌آمیزی طبیعی با گیاهان محلی.",
    businessId: "b004",
    businessName: "کارگاه نساجی رشت",
    businessVerified: true,
    category: "پارچه و نساجی",
    subcategory: "ابریشم",
    price: 380_000,
    originalPrice: 450_000,
    discountPercent: 16,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 31,
    coverGradient: "linear-gradient(135deg, #7C3AED 0%, #4C1D95 100%)",
    inventoryStatus: "low-stock",
    stockCount: 8,
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    city: "رشت",
    tags: ["ابریشم", "پارچه", "دستباف", "گیلان"],
    benefits: ["ابریشم خالص ۱۰۰٪", "بافت دستی سنتی", "رنگ‌آمیزی طبیعی"],
    socialProof: { purchases: 94, views: 782, saves: 47 },
  },

  {
    slug: "coffee-ethiopia",
    name: "قهوه اتیوپی یرگاچف",
    description:
      "دانه‌های قهوه اتیوپی Yirgacheffe با رست ملایم. طعم توت، گل و شکلات تلخ. ۲۰۰ گرمی.",
    businessId: "b005",
    businessName: "کافه رویال رشت",
    businessVerified: true,
    category: "قهوه",
    subcategory: "دانه قهوه",
    price: 245_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 58,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #1C0A00 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    isPublished: true,
    city: "رشت",
    tags: ["قهوه", "اتیوپی", "اسپشیالتی"],
    socialProof: { purchases: 156, views: 820, saves: 72 },
  },

  {
    slug: "shirini-khoshk-gilani",
    name: "شیرینی خشک گیلانی",
    description:
      "مجموعه شیرینی‌های خشک گیلانی شامل کلوچه فومنی، نان‌برنجی و باقلوا با پسته. بسته‌بندی هدیه.",
    businessId: "b003",
    businessName: "شیرینی‌پزی مادربزرگ",
    businessVerified: false,
    category: "شیرینی و دسر",
    subcategory: "شیرینی خشک",
    price: 185_000,
    originalPrice: 220_000,
    discountPercent: 16,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 53,
    coverGradient: "linear-gradient(135deg, #F59E0B 0%, #B45309 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "آمل",
    tags: ["شیرینی", "گیلان", "کلوچه", "هدیه"],
  },

  {
    slug: "chai-sabz-organic-200",
    name: "چای سبز ارگانیک لاهیجان ۲۰۰گرم",
    description:
      "چای سبز ارگانیک از باغ‌های دست‌اول لاهیجان، بدون سم و کود شیمیایی. عطر ملایم و خواص آنتی‌اکسیدان قوی.",
    businessId: "b006",
    businessName: "چایکاری لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "چای سبز",
    price: 185_000,
    originalPrice: 220_000,
    discountPercent: 16,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 93,
    coverGradient: "linear-gradient(135deg, #166534 0%, #14532D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    city: "لاهیجان",
    tags: ["چای سبز", "ارگانیک", "لاهیجان", "گیلان"],
    benefits: ["بدون سم و کود شیمیایی", "مستقیم از باغ", "غنی از آنتی‌اکسیدان"],
    socialProof: { purchases: 287, views: 1435, saves: 124 },
  },

  {
    slug: "chai-momtaz-sargol-500",
    name: "چای ممتاز سرگل لاهیجان ۵۰۰گرم",
    description:
      "چای سرگل بهاره لاهیجان، اولین چین سال با طعم و عطر اعلا. مناسب برای هدیه و مصرف روزانه.",
    businessId: "b006",
    businessName: "چایکاری لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "چای سیاه",
    price: 280_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 147,
    coverGradient: "linear-gradient(135deg, #7C2D12 0%, #431407 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    city: "لاهیجان",
    tags: ["چای", "سرگل", "لاهیجان", "ممتاز"],
    socialProof: { purchases: 412, views: 2060, saves: 189 },
  },

  {
    slug: "baste-hadiyeh-chai",
    name: "بسته هدیه چای لاهیجان",
    description:
      "بسته هدیه ویژه با چای سرگل بهاره، چای سبز ارگانیک و دمنوش گل‌های شمال. جعبه چوبی زیبا.",
    businessId: "b006",
    businessName: "چایکاری لاهیجان",
    businessVerified: true,
    category: "هدیه",
    subcategory: "بسته هدیه",
    price: 320_000,
    originalPrice: 380_000,
    discountPercent: 16,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 47,
    coverGradient: "linear-gradient(135deg, #0D9488 0%, #115E59 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    city: "لاهیجان",
    tags: ["هدیه", "چای", "بسته هدیه"],
    socialProof: { purchases: 128, views: 640, saves: 89 },
  },

  {
    slug: "asal-goon-alborz-1kg",
    name: "عسل گون البرز یک کیلویی",
    description:
      "عسل طبیعی گون از ارتفاعات ۱۸۰۰ متری البرز، بدون هیچ افزودنی. خلوص تضمینی با گواهی آزمایشگاه.",
    businessId: "b007",
    businessName: "زنبورستان البرز",
    businessVerified: true,
    category: "عسل",
    subcategory: "عسل کوهی",
    price: 650_000,
    originalPrice: 750_000,
    discountPercent: 13,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 114,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #92400E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    city: "کرج",
    tags: ["عسل", "کوهی", "طبیعی", "البرز"],
    benefits: ["خلوص ۱۰۰٪ تضمینی", "از ارتفاع ۱۸۰۰ متر", "گواهی آزمایشگاه"],
    socialProof: { purchases: 342, views: 1710, saves: 198 },
  },

  {
    slug: "asal-siyah-dane-500",
    name: "عسل سیاه‌دانه ۵۰۰ گرم",
    description:
      "عسل مخلوط با سیاه‌دانه ارگانیک ایرانی. ترکیب منحصربه‌فرد برای تقویت سیستم ایمنی.",
    businessId: "b007",
    businessName: "زنبورستان البرز",
    businessVerified: true,
    category: "عسل",
    subcategory: "عسل ترکیبی",
    price: 390_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 68,
    coverGradient: "linear-gradient(135deg, #1C1917 0%, #44403C 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "کرج",
    tags: ["عسل", "سیاه‌دانه", "ارگانیک"],
  },

  {
    slug: "jovaher-nogre-dast-saz",
    name: "دستبند نقره فیروزه نیشابور",
    description:
      "دستبند نقره ۹۲۵ استرلینگ با فیروزه اصل نیشابور، ساخت دستی استاد نوروزی. گارانتی ۶ ماهه.",
    businessId: "b008",
    businessName: "جواهرات مهر گیلان",
    businessVerified: true,
    category: "جواهرات",
    subcategory: "دستبند",
    price: 480_000,
    originalPrice: 580_000,
    discountPercent: 17,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 28,
    coverGradient: "linear-gradient(135deg, #0891B2 0%, #164E63 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "رشت",
    tags: ["نقره", "فیروزه", "دستبند", "دستساز"],
    benefits: ["نقره ۹۲۵ استرلینگ", "فیروزه اصل نیشابور", "ساخت دستی", "گارانتی ۶ ماه"],
  },

  {
    slug: "krem-abrasan-soorat",
    name: "کرم آبرسان صورت SPF30",
    description:
      "کرم آبرسان روزانه با SPF30، مناسب پوست معمولی تا مختلط. حاوی هیالورونیک اسید و ویتامین C.",
    businessId: "b009",
    businessName: "داروخانه طبیعی شمال",
    businessVerified: true,
    category: "مراقبت پوست",
    subcategory: "کرم روزانه",
    price: 185_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 76,
    coverGradient: "linear-gradient(135deg, #0EA5E9 0%, #0284C7 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    isPublished: true,
    city: "ساری",
    tags: ["کرم", "SPF", "مراقبت پوست"],
  },

  {
    slug: "vitamin-d3-5000",
    name: "ویتامین D3 5000 IU",
    description:
      "مکمل ویتامین D3 با دوز ۵۰۰۰ واحد بین‌المللی. ۶۰ کپسول نرم ژلاتینی برای ۲ ماه مصرف.",
    businessId: "b009",
    businessName: "داروخانه طبیعی شمال",
    businessVerified: true,
    category: "مکمل",
    subcategory: "ویتامین",
    price: 125_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 145,
    coverGradient: "linear-gradient(135deg, #F59E0B 0%, #D97706 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "ساری",
    tags: ["ویتامین D", "مکمل", "سلامت"],
  },

  {
    slug: "safalineh-goldaar",
    name: "سفالینه گل‌دار لاله‌عباسی",
    description:
      "ظرف سفالی دست‌ساز با نقش لاله‌عباسی. مناسب برای دکوراسیون و هدیه.",
    businessId: "b010",
    businessName: "کارگاه سفالگری مازندران",
    businessVerified: false,
    category: "صنایع دستی",
    subcategory: "سفال",
    price: 145_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 19,
    coverGradient: "linear-gradient(135deg, #B45309 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "بابل",
    tags: ["سفال", "دستساز", "صنایع دستی"],
  },

  {
    slug: "dastband-choob-zeytoon",
    name: "دستبند چوب زیتون طبیعی",
    description:
      "دستبند دستساز از چوب زیتون ایرانی. سبک، طبیعی و بادوام. مناسب برای هر دو جنس.",
    businessId: "b010",
    businessName: "کارگاه سفالگری مازندران",
    businessVerified: false,
    category: "جواهرات",
    subcategory: "دستبند",
    price: 85_000,
    currency: "تومان",
    rating: 4.3,
    reviewCount: 14,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    city: "بابل",
    tags: ["دستبند", "چوب", "طبیعی", "دستساز"],
  },

  /* ══ کافه کتاب آرمان (b001) — dashboard products ══════════ */
  {
    slug: "espresso-double",
    name: "اسپرسو دوبل",
    description:
      "قهوه اسپرسو دوبل با دانه‌های برزیلی درجه یک، بافتی کرمی و عطر تند",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "نوشیدنی گرم",
    subcategory: "قهوه",
    price: 45_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 87,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #1C0A00 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    tags: ["قهوه", "اسپرسو", "پرطرفدار"],
  },
  {
    slug: "chocolate-cake",
    name: "کیک شکلاتی خانگی",
    description:
      "کیک مرطوب شکلاتی با گاناش تازه، دستور اختصاصی کافه",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "شیرینی و کیک",
    subcategory: "کیک",
    price: 75_000,
    originalPrice: 90_000,
    discountPercent: 17,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 43,
    coverGradient: "linear-gradient(135deg, #3D1A00 0%, #6B2C07 100%)",
    inventoryStatus: "low-stock",
    stockCount: 5,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    tags: ["کیک", "شکلات", "خانگی"],
  },
  {
    slug: "lahijan-tea-500g",
    name: "چای لاهیجان ۵۰۰ گرمی",
    description:
      "چای بهاره لاهیجان مستقیم از باغ، عطر و طعم بی‌نظیر شمال",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "نوشیدنی گرم",
    subcategory: "چای",
    price: 185_000,
    originalPrice: 220_000,
    discountPercent: 16,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 120,
    coverGradient: "linear-gradient(135deg, #14532D 0%, #064E3B 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    isPublished: true,
    tags: ["چای", "لاهیجان", "شمال", "ارگانیک"],
  },
  {
    slug: "vanilla-latte",
    name: "لاته وانیل",
    description:
      "اسپرسو با شیر بخار داده شده و سیروپ وانیل طبیعی",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "نوشیدنی گرم",
    subcategory: "قهوه",
    price: 65_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 55,
    coverGradient: "linear-gradient(135deg, #FBBF24 0%, #D97706 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    isPublished: true,
    tags: ["لاته", "وانیل", "قهوه شیری"],
  },
  {
    slug: "novel-collection-3",
    name: "بسته سه‌تایی رمان",
    description:
      "سه رمان برگزیده معاصر ایرانی، انتخاب کارشناسی کافه‌کتاب",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "کتاب",
    subcategory: "رمان",
    price: 350_000,
    originalPrice: 420_000,
    discountPercent: 17,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 32,
    coverGradient: "linear-gradient(135deg, #1E40AF 0%, #1D4ED8 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    tags: ["کتاب", "رمان", "پیشنهادی"],
  },
  {
    slug: "cold-brew",
    name: "کلد‌برو",
    description:
      "قهوه سرد ۱۲ ساعته دم‌کشیده، مناسب برای فصل گرما",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "نوشیدنی سرد",
    subcategory: "فراپه",
    price: 70_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 28,
    coverGradient: "linear-gradient(135deg, #0F172A 0%, #1E3A5F 100%)",
    inventoryStatus: "out-of-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    isPublished: false,
    tags: ["قهوه سرد", "تابستانی"],
  },
  {
    slug: "strawberry-mousse",
    name: "موس توت‌فرنگی",
    description:
      "موس سبک و خوشمزه با توت‌فرنگی محلی شمال، تزئین با خامه",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "دسر و بستنی",
    subcategory: "موس",
    price: 55_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 19,
    coverGradient: "linear-gradient(135deg, #BE185D 0%, #9D174D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    tags: ["دسر", "موس", "توت‌فرنگی"],
  },
  {
    slug: "club-sandwich",
    name: "ساندویچ کلوب",
    description:
      "ساندویچ کلوب با نان تست، مرغ گریل، پنیر چدار و سبزیجات تازه",
    businessId: "b001",
    businessName: "کافه کتاب آرمان",
    businessVerified: true,
    category: "غذا و ساندویچ",
    subcategory: "ساندویچ",
    price: 120_000,
    currency: "تومان",
    rating: 4.5,
    reviewCount: 41,
    coverGradient: "linear-gradient(135deg, #B45309 0%, #92400E 100%)",
    inventoryStatus: "pre-order",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    isPublished: true,
    tags: ["ساندویچ", "مرغ", "ناهار"],
  },
];

async function seed() {
  console.log(`Seeding ${products.length} products...`);

  let inserted = 0;
  let updated = 0;

  for (const product of products) {
    const existing = await db
      .select({ id: productsTable.id })
      .from(productsTable)
      .where(eq(productsTable.slug, product.slug))
      .limit(1);

    if (existing.length > 0) {
      await db
        .update(productsTable)
        .set(product)
        .where(eq(productsTable.slug, product.slug));
      updated++;
    } else {
      await db.insert(productsTable).values(product);
      inserted++;
    }

    console.log(
      `  ${existing.length > 0 ? "↻" : "+"} ${product.slug}`,
    );
  }

  console.log(`\n✓ Done: ${inserted} inserted, ${updated} updated`);
}

seed()
  .catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  })
  .finally(() => {
    pool.end().catch(() => {});
  });
