import type { Product } from "./product.types";

export const mockProducts: Product[] = [
  /* ── رستوران سنتی کولی (b001) ──────────────────────── */
  {
    id: "p001",
    slug: "abgoosht-mazandaran",
    name: "آبگوشت دیزی مازندرانی",
    description: "آبگوشت اصیل مازندرانی با گوشت گوسفندی تازه، نخود و سیب‌زمینی. پخته‌شده با دستور سنتی خانواده‌های شمالی، سرو با نان تازه محلی و دوغ کوهی.",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "غذای اصیل",
    price: 89_000,
    originalPrice: 110_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 124,
    coverGradient: "linear-gradient(135deg, #C2410C 0%, #7C2D12 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2026-01-15",
    phone: "011-44567890",
    whatsapp: "09111234567",
    city: "ساری",
    tags: ["آبگوشت", "غذای سنتی", "مازندران", "شمال", "گوشت گوسفندی"],
    benefits: [
      "گوشت گوسفندی تازه روزانه",
      "بدون مواد نگهدارنده",
      "دستور پخت اصیل مازندرانی",
      "سرو با نان تازه محلی",
      "تهیه‌شده توسط آشپز بومی",
      "مناسب سفارش گروهی",
    ],
    eligibleGroups: [
      "دوستداران غذای اصیل ایرانی",
      "خانواده‌های چند نفره",
      "توریست‌های شمال",
      "مهمانی‌های رسمی",
      "علاقه‌مندان به طعم سنتی",
    ],
    faqs: [
      { question: "آیا امکان تحویل درب منزل وجود دارد؟", answer: "بله، سفارش آنلاین با تحویل در محدوده شهر ساری قبول می‌شود." },
      { question: "آیا مواد اولیه حلال هستند؟", answer: "بله، تمامی مواد اولیه حلال و دارای مجوز بهداشت هستند." },
      { question: "حداقل مدت پیش‌سفارش چقدر است؟", answer: "سفارش‌های بیش از ۵ نفر باید ۴ ساعت قبل ثبت شوند." },
      { question: "آیا نسخه گیاهی وجود دارد؟", answer: "متأسفانه نسخه گیاهی این غذا در حال حاضر موجود نیست." },
    ],
    terms: "لطفاً پیش از سفارش با رستوران تماس بگیرید. سفارش‌های بالای ۱۰ نفر نیاز به هماهنگی قبلی دارند. تحویل در محدوده مشخص‌شده انجام می‌شود. پس از تأیید سفارش امکان کنسل وجود ندارد.",
    socialProof: { purchases: 248, views: 1240, saves: 87 },
    ratingBreakdown: [
      { label: "کیفیت غذا", score: 4.9 },
      { label: "تازگی مواد", score: 4.8 },
      { label: "سرعت سرو", score: 4.6 },
      { label: "ارزش قیمت", score: 4.7 },
    ],
    ratingDistribution: [
      { star: 5, count: 89, percent: 72 },
      { star: 4, count: 22, percent: 18 },
      { star: 3, count: 8, percent: 6 },
      { star: 2, count: 3, percent: 2 },
      { star: 1, count: 2, percent: 2 },
    ],
    reviews: [
      { id: "r1", userName: "سارا م.", date: "2026-03-15", rating: 5, text: "واقعاً خوشمزه‌ترین آبگوشتی بود که خورده‌ام! اصیل و طعم واقعی شمال داشت.", pros: ["طعم عالی", "گوشت نرم"], helpful: 12 },
      { id: "r2", userName: "رضا ک.", date: "2026-02-28", rating: 5, text: "دستور پخت سنتی رعایت شده، نان محلی هم همراه داشت. حتماً دوباره سفارش می‌دم.", pros: ["اصالت طعم", "بسته‌بندی مناسب"], helpful: 8 },
      { id: "r3", userName: "نگار ف.", date: "2026-02-10", rating: 4, text: "خوب بود ولی نسبت به دفعه قبل کمی حجمش کمتر بود.", cons: ["حجم کم"], helpful: 4 },
    ],
  },
  {
    id: "p002",
    slug: "mahi-shekampor",
    name: "ماهی شکم‌پر دریای خزر",
    description: "ماهی تازه خزر با پرکردن سبزی‌های بومی — رازیانه، گشنیز، تره‌فرنگی — و ادویه‌های محلی. کباب‌شده روی آتش ذغال و سرو با برنج دمی و سبزی خوردن.",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "دریایی",
    price: 145_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 89,
    coverGradient: "linear-gradient(135deg, #0369A1 0%, #082F49 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2026-01-10",
    phone: "011-44567890",
    whatsapp: "09111234567",
    city: "ساری",
    tags: ["ماهی", "غذای دریایی", "خزر", "کباب", "شمال"],
    benefits: [
      "ماهی تازه صید روز از خزر",
      "بدون رنگ و مواد نگهدارنده",
      "سبزی محلی بومی گردآوری‌شده",
      "پخت سنتی روی آتش ذغال",
      "سرو با برنج دمی خوش‌طعم",
    ],
    eligibleGroups: [
      "دوستداران غذاهای دریایی",
      "خانواده‌های ۲ تا ۴ نفره",
      "توریست‌های شمال ایران",
      "علاقه‌مندان به طبخ سنتی",
    ],
    faqs: [
      { question: "آیا ماهی تازه است؟", answer: "بله، ماهی‌ها هر روز صبح از ساحل خریداری می‌شوند." },
      { question: "آیا امکان پیش‌سفارش وجود دارد؟", answer: "بله، یک روز قبل می‌توانید سفارش خود را ثبت کنید." },
      { question: "نوع ماهی چیست؟", answer: "معمولاً کپور، آمور یا ماهی سفید خزر استفاده می‌شود." },
    ],
    terms: "ماهی دریایی محدودیت تعداد دارد. سفارش بالای ۳ عدد نیاز به هماهنگی یک روز قبل دارد.",
    socialProof: { purchases: 312, views: 1560, saves: 105 },
    ratingBreakdown: [
      { label: "تازگی ماهی", score: 5.0 },
      { label: "طعم و ادویه", score: 4.9 },
      { label: "حجم غذا", score: 4.7 },
      { label: "ارزش قیمت", score: 4.8 },
    ],
    ratingDistribution: [
      { star: 5, count: 72, percent: 81 },
      { star: 4, count: 12, percent: 13 },
      { star: 3, count: 4, percent: 4 },
      { star: 2, count: 1, percent: 1 },
      { star: 1, count: 0, percent: 0 },
    ],
    reviews: [
      { id: "r1", userName: "علی ح.", date: "2026-04-02", rating: 5, text: "بهترین ماهی شکم‌پری که تا به حال خورده‌ام! سبزی‌ها کاملاً تازه بودند.", pros: ["تازگی ماهی", "سبزی بومی"], helpful: 18 },
      { id: "r2", userName: "مریم ت.", date: "2026-03-20", rating: 5, text: "رستوران کولی همیشه کیفیت ثابت دارد. این ماهی شاهکار بود.", pros: ["کیفیت ثابت", "برنج عالی"], helpful: 14 },
    ],
    followerCount: 215,
  },
  {
    id: "p003",
    slug: "morgh-torsh-gilani",
    name: "مرغ ترش گیلانی",
    description: "مرغ با آلوچه تازه گیلان، گردوی محلی و رب انار خانگی — طعم اصیل شمالی که یادآور خانه مادربزرگ است. سرو با برنج کته و سبزی.",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "مرغ",
    price: 95_000,
    originalPrice: 115_000,
    discountPercent: 17,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 67,
    coverGradient: "linear-gradient(135deg, #65A30D 0%, #365314 100%)",
    inventoryStatus: "low-stock",
    stockCount: 8,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-03-01",
    phone: "011-44567890",
    whatsapp: "09111234567",
    city: "ساری",
    tags: ["مرغ ترش", "گیلانی", "رب انار", "غذای سنتی", "آلوچه"],
    benefits: [
      "آلوچه تازه محلی گیلان",
      "رب انار خانگی بدون افزودنی",
      "گردوی محلی شمال",
      "دستور پخت نسل به نسل",
      "بدون رنگ مصنوعی",
    ],
    eligibleGroups: [
      "علاقه‌مندان به غذای اصیل شمالی",
      "خانواده‌های ۲ تا ۳ نفره",
      "کسانی که ترشی دوست دارند",
    ],
    faqs: [
      { question: "طعم ترش آن چقدر زیاد است؟", answer: "طعم ترشی متعادل است و برای اکثر ذائقه‌ها مناسب." },
      { question: "آیا گیاهی‌خواران می‌توانند سفارش دهند؟", answer: "خیر، این غذا حاوی مرغ است." },
      { question: "با چه نانی سرو می‌شود؟", answer: "با برنج کته و نان محلی سرو می‌شود." },
    ],
    terms: "به دلیل موجودی محدود (۸ عدد)، پیش‌سفارش توصیه می‌شود.",
    socialProof: { purchases: 178, views: 890, saves: 63 },
    ratingBreakdown: [
      { label: "طعم ترشی", score: 4.8 },
      { label: "کیفیت مرغ", score: 4.7 },
      { label: "ارزش قیمت", score: 4.6 },
      { label: "تازگی مواد", score: 4.7 },
    ],
    ratingDistribution: [
      { star: 5, count: 45, percent: 67 },
      { star: 4, count: 15, percent: 22 },
      { star: 3, count: 5, percent: 7 },
      { star: 2, count: 2, percent: 3 },
      { star: 1, count: 0, percent: 0 },
    ],
    reviews: [
      { id: "r1", userName: "فاطمه ر.", date: "2026-03-28", rating: 5, text: "مرغ ترش اصیل گیلانی! دقیقاً همان طعمی که دنبالش بودم.", pros: ["طعم اصیل", "ترشی درست"], helpful: 11 },
      { id: "r2", userName: "حسن م.", date: "2026-03-15", rating: 4, text: "خوب بود ولی دفعه قبل کمی خوش‌طعم‌تر بود.", pros: ["گردوی خوب"], cons: ["طعم یکنواخت نیست"], helpful: 6 },
    ],
    followerCount: 143,
  },
  {
    id: "p004",
    slug: "bamiyeh-ba-asal",
    name: "دسر بامیه با عسل طبیعی",
    description: "بامیه سرخ‌شده با شربت عسل و گلاب — دسر خانگی روز",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "دسر",
    subcategory: "شیرینی",
    price: 35_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 43,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-12-20",
  },

  /* ── فروشگاه پارچه ابریشم گیلان (b002) ─────────────── */
  {
    id: "p005",
    slug: "abrisham-rasht-1m",
    name: "پارچه ابریشم اصل رشت ۱ متر",
    description: "ابریشم تابنده خالص، بافت سنتی گیلان، رنگ‌آمیزی طبیعی",
    businessId: "b002",
    businessName: "فروشگاه پارچه ابریشم گیلان",
    businessVerified: true,
    category: "پارچه و نساجی",
    subcategory: "ابریشم",
    price: 890_000,
    originalPrice: 1_100_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 56,
    coverGradient: "linear-gradient(135deg, #9333EA 0%, #4C1D95 100%)",
    inventoryStatus: "low-stock",
    stockCount: 12,
    isInstallmentAvailable: true,
    installmentMonths: 3,
    installmentMonthlyAmount: 296_667,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-11-01",
    phone: "013-33445566",
    whatsapp: "09121234567",
    city: "رشت",
    tags: ["ابریشم", "پارچه سنتی", "گیلان", "دست‌بافت", "رنگ طبیعی"],
    benefits: [
      "ابریشم خالص تأیید‌شده ۱۰۰٪",
      "رنگ‌آمیزی با رنگ‌های گیاهی طبیعی",
      "بافت دستی توسط استادکاران گیلانی",
      "مناسب خیاطی لباس مجلسی و شال",
      "گواهینامه اصالت پارچه دارد",
    ],
    eligibleGroups: [
      "خیاطان حرفه‌ای",
      "علاقه‌مندان به هنر بومی",
      "خریداران هدیه لوکس",
      "فروشگاه‌های پوشاک سنتی",
    ],
    faqs: [
      { question: "آیا این پارچه قابل شستشو با ماشین است؟", answer: "خیر، فقط با دست یا خشکشویی تخصصی شسته شود." },
      { question: "آیا ارسال به تهران دارید؟", answer: "بله، ارسال پستی به سراسر کشور داریم." },
      { question: "تفاوت این پارچه با ابریشم چینی چیست؟", answer: "ابریشم گیلان دست‌بافت است و رنگ‌آمیزی طبیعی دارد، درحالی‌که ابریشم چینی ماشینی و رنگ‌آمیزی صنعتی دارد." },
      { question: "آیا نمونه رنگ‌بندی دارید؟", answer: "بله، با تماس با فروشگاه نمونه‌های رنگی رایگان ارسال می‌کنیم." },
    ],
    terms: "پارچه قابل مرجوعی نیست مگر در صورت عیب کارخانه. رنگ واقعی ممکن است کمی با نمایش صفحه متفاوت باشد.",
    socialProof: { purchases: 134, views: 2100, saves: 198 },
    ratingBreakdown: [
      { label: "کیفیت ابریشم", score: 5.0 },
      { label: "اصالت رنگ", score: 4.9 },
      { label: "ظرافت بافت", score: 4.9 },
      { label: "ارزش قیمت", score: 4.7 },
    ],
    ratingDistribution: [
      { star: 5, count: 44, percent: 79 },
      { star: 4, count: 9, percent: 16 },
      { star: 3, count: 2, percent: 4 },
      { star: 2, count: 1, percent: 2 },
      { star: 1, count: 0, percent: 0 },
    ],
    reviews: [
      { id: "r1", userName: "زینب ا.", date: "2026-02-14", rating: 5, text: "بهترین ابریشمی که تا به حال خریدم. لمس فوق‌العاده‌ای دارد، کاملاً اصل است.", pros: ["لمس عالی", "رنگ ثابت"], helpful: 22 },
      { id: "r2", userName: "شیرین ک.", date: "2026-01-30", rating: 5, text: "برای لباس عروسی استفاده کردم. خیاط هم از کیفیتش تعریف کرد.", pros: ["قابل دوخت", "رنگ زیبا"], helpful: 17 },
      { id: "r3", userName: "نادر م.", date: "2025-12-20", rating: 4, text: "کیفیت خوب است ولی قیمتش بالاست. ارزش دارد اما برای همه مناسب نیست.", cons: ["قیمت بالا"], helpful: 9 },
    ],
    followerCount: 312,
  },
  {
    id: "p006",
    slug: "roosari-abrisham",
    name: "روسری ابریشم دست‌بافت",
    description: "روسری خالص ابریشم با نقوش گلدار سنتی گیلان، در ابعاد ۱۴۰×۱۴۰",
    businessId: "b002",
    businessName: "فروشگاه پارچه ابریشم گیلان",
    businessVerified: true,
    category: "پوشاک",
    subcategory: "روسری",
    price: 450_000,
    originalPrice: 580_000,
    discountPercent: 22,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 38,
    coverGradient: "linear-gradient(135deg, #EC4899 0%, #831843 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-10-15",
  },
  {
    id: "p007",
    slug: "charghad-termeh",
    name: "چارقد ترمه گیلان",
    description: "چارقد ترمه‌بافت اصیل، ۱۰۰٪ پشم، طرح سنتی",
    businessId: "b002",
    businessName: "فروشگاه پارچه ابریشم گیلان",
    businessVerified: true,
    category: "پوشاک",
    subcategory: "روسری",
    price: 280_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 29,
    coverGradient: "linear-gradient(135deg, #7C3AED 0%, #2E1065 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-02-10",
  },

  /* ── کافه و شیرینی جنگل (b003) ─────────────────────── */
  {
    id: "p008",
    slug: "cake-jangali",
    name: "کیک جنگلی خانگی ۸ نفره",
    description: "کیک اسفنجی با خامه گردو، گیلاس تازه و شکلات تلخ",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "شیرینی و دسر",
    subcategory: "کیک",
    price: 75_000,
    originalPrice: 95_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 182,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-12-05",
  },
  {
    id: "p009",
    slug: "coffee-ethiopia",
    name: "قهوه اسپشیالتی اتیوپی",
    description: "دانه قهوه اتیوپی Yirgacheffe، رست ملایم، نت‌های توت و گل",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "قهوه",
    subcategory: "دانه قهوه",
    price: 42_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 97,
    coverGradient: "linear-gradient(135deg, #292524 0%, #1C1917 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-11-20",
  },
  {
    id: "p010",
    slug: "shirini-khoshk-gilani",
    name: "شیرینی خشک گیلانی ۵۰۰ گرم",
    description: "شیرینی ناپلئونی، نان برنجی و کماج — بسته هدیه مخصوص",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "شیرینی و دسر",
    subcategory: "شیرینی خشک",
    price: 55_000,
    originalPrice: 68_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 64,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #92400E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-10-10",
  },
  {
    id: "p011",
    slug: "smoothie-jangali",
    name: "اسموتی جنگلی تازه",
    description: "توت فرنگی، موز، اسفناج بچه و شیر بادام — بدون شکر اضافه",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "نوشیدنی",
    subcategory: "اسموتی",
    price: 28_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 51,
    coverGradient: "linear-gradient(135deg, #15803D 0%, #052E16 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-03-15",
  },

  /* ── آتلیه عکاسی نور ساری (b004) ─────────────────────── */
  {
    id: "p012",
    slug: "pakij-akasi-portere-1h",
    name: "پکیج عکاسی پرتره ۱ ساعته",
    description: "۳۰ عکس ویرایش‌شده حرفه‌ای، فایل RAW، تحویل ۴۸ ساعته",
    businessId: "b004",
    businessName: "آتلیه عکاسی نور ساری",
    businessVerified: true,
    category: "خدمات عکاسی",
    subcategory: "پرتره",
    price: 450_000,
    originalPrice: 600_000,
    discountPercent: 25,
    currency: "تومان",
    rating: 5.0,
    reviewCount: 43,
    coverGradient: "linear-gradient(135deg, #1860DB 0%, #0A2660 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-09-01",
  },
  {
    id: "p013",
    slug: "pakij-akasi-mahsol-20",
    name: "پکیج عکاسی محصول ۲۰ تصویر",
    description: "عکاسی محصول حرفه‌ای برای فروشگاه آنلاین، بک‌گراند سفید و رنگی",
    businessId: "b004",
    businessName: "آتلیه عکاسی نور ساری",
    businessVerified: true,
    category: "خدمات عکاسی",
    subcategory: "محصول",
    price: 1_200_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 28,
    coverGradient: "linear-gradient(135deg, #0284C7 0%, #0C4A6E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-08-20",
  },
  {
    id: "p014",
    slug: "video-tablighati-30s",
    name: "ویدیوی تبلیغاتی ۳۰ ثانیه‌ای",
    description: "تولید محتوای ویدیویی حرفه‌ای برای اینستاگرام و تلگرام",
    businessId: "b004",
    businessName: "آتلیه عکاسی نور ساری",
    businessVerified: true,
    category: "خدمات تبلیغاتی",
    subcategory: "ویدیو",
    price: 2_800_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 17,
    coverGradient: "linear-gradient(135deg, #6366F1 0%, #312E81 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 6,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-07-15",
  },

  /* ── داروخانه شبانه‌روزی شفا (b005) ─────────────────── */
  {
    id: "p015",
    slug: "vitamin-d3-5000",
    name: "ویتامین D3 5000 واحد ۶۰ عدد",
    description: "ویتامین D3 با جذب بالا، ساخت داروسازی معتبر",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مکمل",
    subcategory: "ویتامین",
    price: 85_000,
    originalPrice: 105_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 93,
    coverGradient: "linear-gradient(135deg, #FBBF24 0%, #D97706 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-11-05",
  },
  {
    id: "p016",
    slug: "omega3-giyahi",
    name: "امگا-۳ گیاهی ۹۰ کپسول",
    description: "روغن بذر کتان و چیا، منبع طبیعی امگا-۳ بدون عطر ماهی",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مکمل",
    subcategory: "روغن",
    price: 145_000,
    currency: "تومان",
    rating: 4.5,
    reviewCount: 47,
    coverGradient: "linear-gradient(135deg, #34D399 0%, #065F46 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-02-20",
  },
  {
    id: "p017",
    slug: "krem-abrasan-soorat",
    name: "کرم آبرسان روز صورت SPF30",
    description: "کرم مرطوب‌کننده با فاکتور ضدآفتاب، مناسب پوست معمولی تا مختلط",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مراقبت پوست",
    subcategory: "کرم روز",
    price: 220_000,
    originalPrice: 290_000,
    discountPercent: 24,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 62,
    coverGradient: "linear-gradient(135deg, #F9A8D4 0%, #9D174D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-10-25",
  },
  {
    id: "p018",
    slug: "mask-shab-retinol",
    name: "ماسک شب رتینول ۰.۳٪",
    description: "ماسک ضدپیری شبانه با رتینول و نیاسینامید، کاهش خطوط ظریف",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مراقبت پوست",
    subcategory: "ماسک",
    price: 180_000,
    originalPrice: 240_000,
    discountPercent: 25,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 34,
    coverGradient: "linear-gradient(135deg, #FED7AA 0%, #9A3412 100%)",
    inventoryStatus: "low-stock",
    stockCount: 5,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-09-30",
  },

  /* ── صنایع دستی نوروزی (b006) ───────────────────────── */
  {
    id: "p019",
    slug: "safalineh-goldaar",
    name: "سفالینه گل‌دار دست‌ساز",
    description: "کاسه سفالی با نقش گل و مرغ، لعاب آبی کبالت، کوره‌پخت ۱۲۸۰ درجه",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "صنایع دستی",
    subcategory: "سفال",
    price: 320_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 28,
    coverGradient: "linear-gradient(135deg, #B45309 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-08-10",
  },
  {
    id: "p020",
    slug: "tablou-hasir-mazandaran",
    name: "تابلوی حصیربافی مازندران",
    description: "تابلو دیواری حصیربافی دست‌ساز با نقش طبیعت شمال، ابعاد ۶۰×۴۰",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "صنایع دستی",
    subcategory: "حصیربافی",
    price: 550_000,
    originalPrice: 700_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 19,
    coverGradient: "linear-gradient(135deg, #92400E 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-07-20",
  },
  {
    id: "p021",
    slug: "zarf-choobi-naghsh",
    name: "ظرف چوبی منبت‌کاری شده",
    description: "کاسه چوب گردو با کنده‌کاری دستی طرح اسلیمی",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "صنایع دستی",
    subcategory: "چوب",
    price: 185_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 22,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #3B1A0D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-06-15",
  },
  {
    id: "p022",
    slug: "jovaher-nogre-dast-saz",
    name: "گوشواره نقره دست‌ساز گیلان",
    description: "نقره ۹۲۵ با سنگ فیروزه اصل نیشابور، دست‌ساز استاد نوروزی",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "جواهرات",
    subcategory: "گوشواره",
    price: 480_000,
    originalPrice: 620_000,
    discountPercent: 23,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 41,
    coverGradient: "linear-gradient(135deg, #71717A 0%, #18181B 100%)",
    inventoryStatus: "low-stock",
    stockCount: 3,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-05-28",
  },
  {
    id: "p023",
    slug: "dastband-choob-zeytoon",
    name: "دستبند چوب زیتون گیلان",
    description: "دستبند زیتون کوهی با حلقه‌های دستی، هر قطعه منحصربه‌فرد",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "جواهرات",
    subcategory: "دستبند",
    price: 95_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 37,
    coverGradient: "linear-gradient(135deg, #A16207 0%, #3B1A0D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-01-30",
  },

  /* ── چای‌خانه سبز لاهیجان (b007) ──────────────────── */
  {
    id: "p024",
    slug: "chai-sabz-organic-200",
    name: "چای سبز ارگانیک لاهیجان ۲۰۰ گرم",
    description: "چای سبز درجه‌یک، بدون سم، چیده‌شده اواخر بهار",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "چای سبز",
    price: 120_000,
    originalPrice: 155_000,
    discountPercent: 23,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 134,
    coverGradient: "linear-gradient(135deg, #15803D 0%, #052E16 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-09-05",
  },
  {
    id: "p025",
    slug: "chai-momtaz-sargol-500",
    name: "چای ممتاز سرگل لاهیجان ۵۰۰ گرم",
    description: "چای قلم ممتاز، بسته‌بندی هدیه، رنگ طلایی و طعم گل",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "چای سیاه",
    price: 320_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 87,
    coverGradient: "linear-gradient(135deg, #16A34A 0%, #052E16 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-08-15",
  },
  {
    id: "p026",
    slug: "damnoosh-gol-gaozaban",
    name: "دمنوش گل گاوزبان ۱۰۰ گرم",
    description: "گل گاوزبان خشک‌شده در سایه از مراتع شمال — آرام‌بخش طبیعی",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "دمنوش",
    subcategory: "گیاهی",
    price: 85_000,
    originalPrice: 105_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 62,
    coverGradient: "linear-gradient(135deg, #7C3AED 0%, #2E1065 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-07-10",
  },
  {
    id: "p027",
    slug: "chai-irani-mokhallat",
    name: "چای مخلوط ایرانی ویژه",
    description: "ترکیب اختصاصی چای قلم، هل، زعفران و گلاب — طعم شرقی",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "ترکیبی",
    price: 180_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 94,
    coverGradient: "linear-gradient(135deg, #B91C1C 0%, #450A0A 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-06-25",
  },
  {
    id: "p028",
    slug: "baste-hadiyeh-chai",
    name: "بسته هدیه چای لاهیجان پرمیوم",
    description: "جعبه چوبی شامل سرگل، چای سبز، دمنوش و عسل — ایده‌آل هدیه",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "هدیه",
    subcategory: "بسته هدیه",
    price: 450_000,
    originalPrice: 580_000,
    discountPercent: 22,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 48,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-05-10",
  },

  /* ── زنبورداری کوه‌نشین البرز (b008) ─────────────────── */
  {
    id: "p029",
    slug: "asal-goon-alborz-1kg",
    name: "عسل طبیعی گون البرز ۱ کیلو",
    description: "عسل گون خالص، ۱۰۰٪ طبیعی، بدون افزودنی، با شناسنامه زنبورستان",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "عسل",
    subcategory: "عسل طبیعی",
    price: 380_000,
    originalPrice: 490_000,
    discountPercent: 22,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 112,
    coverGradient: "linear-gradient(135deg, #F59E0B 0%, #92400E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-08-01",
  },
  {
    id: "p030",
    slug: "asal-siyah-dane-500",
    name: "عسل سیاه‌دانه کوهستانی ۵۰۰ گرم",
    description: "عسل با عصاره سیاه‌دانه تقویت‌شده — تقویت سیستم ایمنی",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "عسل",
    subcategory: "عسل دارویی",
    price: 210_000,
    originalPrice: 265_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 76,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-07-05",
  },
  {
    id: "p031",
    slug: "moum-zanboor-100g",
    name: "موم زنبور طبیعی ۱۰۰ گرم",
    description: "موم خام طبیعی برای ساخت کرم، شمع و محصولات مراقبتی",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "محصولات زنبور",
    subcategory: "موم",
    price: 85_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 34,
    coverGradient: "linear-gradient(135deg, #FBBF24 0%, #B45309 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-06-10",
  },
  {
    id: "p032",
    slug: "propolis-khales-100",
    name: "پروپولیس خالص ۱۰۰ گرم",
    description: "پروپولیس خام با خلوص ۸۰٪+، آنتی‌بیوتیک طبیعی زنبور عسل",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "محصولات زنبور",
    subcategory: "پروپولیس",
    price: 165_000,
    originalPrice: 210_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 58,
    coverGradient: "linear-gradient(135deg, #A16207 0%, #3B1A0D 100%)",
    inventoryStatus: "low-stock",
    stockCount: 7,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-05-15",
  },
];

/* ── Derived helpers ─────────────────────────────────── */
export const getFeaturedProducts = () =>
  mockProducts.filter(p => p.isFeatured);

export const getDealProducts = () =>
  mockProducts
    .filter(p => p.discountPercent && p.discountPercent >= 19)
    .sort((a, b) => (b.discountPercent ?? 0) - (a.discountPercent ?? 0));

export const getInstallmentProducts = () =>
  mockProducts.filter(p => p.isInstallmentAvailable);

export const getProductsByBusiness = (businessId: string) =>
  mockProducts.filter(p => p.businessId === businessId);

export const getNewProducts = () =>
  mockProducts.filter(p => p.isNew);
