import type { Business } from "./business.types";

export const mockBusinesses: Business[] = [
  {
    id: "b001",
    slug: "restaurant-kooli-babol",
    name: "رستوران سنتی کولی",
    description: "قدیمی‌ترین رستوران سنتی بابل با منوی اصیل مازندرانی. غذاهای دریایی تازه، آبگوشت محلی و نان‌های سنتی.",
    coverGradient: "linear-gradient(135deg, #EA580C 0%, #7C2D12 100%)",
    logoColor: "#EA580C",
    category: "رستوران",
    subcategory: "غذای محلی",
    tags: ["غذای محلی", "دریایی", "سنتی", "مازندران"],
    city: "بابل",
    province: "مازندران",
    address: "خیابان شریعتی، نبش کوچه باغ",
    latitude: 36.5513,
    longitude: 52.6789,
    distance: "۱.۲ کیلومتر",
    phone: "011-32XXXXXX",
    rating: 4.9,
    reviewCount: 312,
    followersCount: 1840,
    verificationStatus: "verified",
    promoted: true,
    featured: true,
    isOpen: true,
    opensAt: "11:00",
    closesAt: "23:00",
    responseRate: 97,
    gallery: [
      "linear-gradient(135deg, #F97316 0%, #7C2D12 100%)",
      "linear-gradient(135deg, #EF4444 0%, #B91C1C 100%)",
      "linear-gradient(135deg, #FBBF24 0%, #D97706 100%)",
    ],
  },
  {
    id: "b002",
    slug: "abrisham-gallery-rasht",
    name: "فروشگاه پارچه ابریشم گیلان",
    description: "عرضه مستقیم پارچه‌های ابریشمی اصل گیلان. تولید محلی با صد سال سابقه هنری.",
    coverGradient: "linear-gradient(135deg, #7C3AED 0%, #2E1065 100%)",
    logoColor: "#7C3AED",
    category: "پارچه و خیاطی",
    subcategory: "صنایع دستی",
    tags: ["ابریشم اصل", "سنتی", "هدیه", "دست‌بافت"],
    city: "رشت",
    province: "گیلان",
    address: "بازار بزرگ رشت، راسته پارچه‌فروشان",
    latitude: 37.2808,
    longitude: 49.5832,
    distance: "۳.۵ کیلومتر",
    phone: "013-33XXXXXX",
    rating: 4.7,
    reviewCount: 189,
    followersCount: 940,
    verificationStatus: "verified",
    promoted: false,
    featured: true,
    isOpen: true,
    opensAt: "09:00",
    closesAt: "20:30",
    responseRate: 88,
    gallery: [
      "linear-gradient(135deg, #8B5CF6 0%, #4C1D95 100%)",
      "linear-gradient(135deg, #EC4899 0%, #831843 100%)",
    ],
  },
  {
    id: "b003",
    slug: "cafe-jungle-nowshahr",
    name: "کافه و شیرینی جنگل",
    description: "جذاب‌ترین کافه نوشهر در دل جنگل. قهوه تخصصی، کیک‌های خانگی، فضای منحصربه‌فرد.",
    coverGradient: "linear-gradient(135deg, #15803D 0%, #052E16 100%)",
    logoColor: "#15803D",
    category: "کافه",
    subcategory: "قهوه تخصصی",
    tags: ["قهوه تخصصی", "کیک", "دنج", "جنگل"],
    city: "نوشهر",
    province: "مازندران",
    address: "جاده هراز، کیلومتر ۳",
    latitude: 36.6482,
    longitude: 51.4956,
    distance: "۰.۸ کیلومتر",
    phone: "011-46XXXXXX",
    rating: 4.8,
    reviewCount: 421,
    followersCount: 2310,
    verificationStatus: "verified",
    promoted: true,
    featured: false,
    isOpen: false,
    opensAt: "09:00",
    closesAt: "22:00",
    responseRate: 91,
    gallery: [
      "linear-gradient(135deg, #22C55E 0%, #14532D 100%)",
      "linear-gradient(135deg, #84CC16 0%, #365314 100%)",
    ],
  },
  {
    id: "b004",
    slug: "noor-studio-sari",
    name: "آتلیه عکاسی نور ساری",
    description: "استودیو حرفه‌ای عکاسی پرتره، مجالس و تبلیغاتی در ساری. بهترین تجهیزات، تجربه ۱۵ ساله.",
    coverGradient: "linear-gradient(135deg, #1860DB 0%, #0A2660 100%)",
    logoColor: "#1860DB",
    category: "عکاسی",
    subcategory: "پرتره",
    tags: ["پرتره", "مجالس", "محصول", "حرفه‌ای"],
    city: "ساری",
    province: "مازندران",
    address: "خیابان فرهنگ، پلاک ۱۲",
    latitude: 36.5633,
    longitude: 53.0601,
    distance: "۲.۱ کیلومتر",
    phone: "011-33XXXXXX",
    rating: 4.9,
    reviewCount: 97,
    followersCount: 672,
    verificationStatus: "verified",
    promoted: false,
    featured: false,
    isOpen: true,
    opensAt: "10:00",
    closesAt: "21:00",
    responseRate: 99,
    gallery: [
      "linear-gradient(135deg, #3B82F6 0%, #1E3A8A 100%)",
      "linear-gradient(135deg, #6366F1 0%, #312E81 100%)",
    ],
  },
  {
    id: "b005",
    slug: "shafa-pharmacy-amol",
    name: "داروخانه شبانه‌روزی شفا",
    description: "داروخانه کامل با پزشک مشاور آنلاین. داروهای تخصصی، مکمل‌ها و لوازم پزشکی.",
    coverGradient: "linear-gradient(135deg, #DC2626 0%, #7F1D1D 100%)",
    logoColor: "#DC2626",
    category: "داروخانه",
    subcategory: "بهداشت",
    tags: ["شبانه‌روزی", "ارسال سریع", "تخصصی", "مشاوره"],
    city: "آمل",
    province: "مازندران",
    address: "میدان امام، ابتدای خیابان طالقانی",
    latitude: 36.4700,
    longitude: 52.3573,
    distance: "۰.۵ کیلومتر",
    phone: "011-44XXXXXX",
    rating: 4.6,
    reviewCount: 243,
    followersCount: 1130,
    verificationStatus: "verified",
    promoted: false,
    featured: false,
    isOpen: true,
    closesAt: "24:00",
    responseRate: 95,
    gallery: [],
  },
  {
    id: "b006",
    slug: "noroozi-handicrafts-lahijan",
    name: "صنایع دستی نوروزی",
    description: "بزرگ‌ترین مجموعه صنایع دستی استان گیلان. حصیربافی، سفال، جواهرات دست‌ساز.",
    coverGradient: "linear-gradient(135deg, #D97706 0%, #451A03 100%)",
    logoColor: "#D97706",
    category: "صنایع دستی",
    subcategory: "هنر بومی",
    tags: ["حصیر", "سفال", "جواهرات", "دست‌ساز", "هدیه"],
    city: "لاهیجان",
    province: "گیلان",
    address: "بلوار شهید بهشتی، مقابل پارک",
    latitude: 37.2107,
    longitude: 50.0072,
    distance: "۵.۰ کیلومتر",
    phone: "013-42XXXXXX",
    rating: 4.8,
    reviewCount: 64,
    followersCount: 487,
    verificationStatus: "verified",
    promoted: false,
    featured: false,
    isOpen: true,
    opensAt: "09:00",
    closesAt: "19:00",
    responseRate: 82,
    gallery: [
      "linear-gradient(135deg, #F59E0B 0%, #B45309 100%)",
    ],
  },
  {
    id: "b007",
    slug: "sabz-tea-lahijan",
    name: "چای‌خانه سبز لاهیجان",
    description: "مستقیم از باغ‌های چای لاهیجان. چای ارگانیک، سرویس هدیه، ارسال سراسری.",
    coverGradient: "linear-gradient(135deg, #16A34A 0%, #052E16 100%)",
    logoColor: "#16A34A",
    category: "مواد غذایی",
    subcategory: "چای و دمنوش",
    tags: ["چای ارگانیک", "باغ چای", "هدیه", "لاهیجان"],
    city: "لاهیجان",
    province: "گیلان",
    address: "جاده لاهیجان-رشت کیلومتر ۲",
    latitude: 37.2031,
    longitude: 50.0051,
    distance: "۴.۳ کیلومتر",
    phone: "013-42XXXXXX",
    rating: 4.9,
    reviewCount: 213,
    followersCount: 2140,
    verificationStatus: "verified",
    promoted: true,
    featured: false,
    isOpen: true,
    opensAt: "08:00",
    closesAt: "20:00",
    responseRate: 94,
    gallery: [
      "linear-gradient(135deg, #4ADE80 0%, #166534 100%)",
    ],
  },
  {
    id: "b008",
    slug: "alborz-honey-nowshahr",
    name: "زنبورداری کوه‌نشین البرز",
    description: "عسل طبیعی کوهستانی مستقیم از دامنه البرز. ۱۰۰٪ خالص، بدون افزودنی.",
    coverGradient: "linear-gradient(135deg, #F59E0B 0%, #78350F 100%)",
    logoColor: "#F59E0B",
    category: "مواد غذایی",
    subcategory: "محصولات طبیعی",
    tags: ["عسل طبیعی", "کوهستانی", "ارگانیک", "تضمین کیفیت"],
    city: "نوشهر",
    province: "مازندران",
    address: "روستای ونوش، کیلومتر ۱۵ جاده هراز",
    latitude: 36.6523,
    longitude: 51.4841,
    distance: "۱۸.۰ کیلومتر",
    phone: "011-46XXXXXX",
    rating: 4.9,
    reviewCount: 156,
    followersCount: 890,
    verificationStatus: "verified",
    promoted: false,
    featured: false,
    isOpen: true,
    opensAt: "08:00",
    closesAt: "18:00",
    responseRate: 79,
    gallery: [],
  },
];

export const getFeaturedBusinesses = () =>
  mockBusinesses.filter(b => b.featured);

export const getPromotedBusinesses = () =>
  mockBusinesses.filter(b => b.promoted);

export const getBusinessBySlug = (slug: string) =>
  mockBusinesses.find(b => b.slug === slug);
