import type { Product } from "./product.types";

export const mockProducts: Product[] = [
  /* ── رستوران سنتی کولی (b001) ──────────────────────── */
  {
    id: "p001",
    slug: "abgoosht-mazandaran",
    name: "آبگوشت دیزی مازندرانی",
    description: "آبگوشت اصیل مازندرانی با گوشت گوسفندی تازه، نخود و سیب‌زمینی",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "غذای اصیل",
    price: 89_000,
    originalPrice: 110_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 124,
    coverGradient: "linear-gradient(135deg, #C2410C 0%, #7C2D12 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2026-01-15",
  },
  {
    id: "p002",
    slug: "mahi-shekampor",
    name: "ماهی شکم‌پر دریای خزر",
    description: "ماهی تازه شمال با پر کردن سبزی‌های محلی، سرخ شده در تابه",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "دریایی",
    price: 145_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 89,
    coverGradient: "linear-gradient(135deg, #0369A1 0%, #082F49 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2026-01-10",
  },
  {
    id: "p003",
    slug: "morgh-torsh-gilani",
    name: "مرغ ترش گیلانی",
    description: "مرغ با آلوچه، گردو و رب انار — طعم اصیل شمالی",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "غذای محلی",
    subcategory: "مرغ",
    price: 95_000,
    originalPrice: 115_000,
    discountPercent: 17,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 67,
    coverGradient: "linear-gradient(135deg, #65A30D 0%, #365314 100%)",
    inventoryStatus: "low-stock",
    stockCount: 8,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-03-01",
  },
  {
    id: "p004",
    slug: "bamiyeh-ba-asal",
    name: "دسر بامیه با عسل طبیعی",
    description: "بامیه سرخ‌شده با شربت عسل و گلاب — دسر خانگی روز",
    businessId: "b001",
    businessName: "رستوران سنتی کولی",
    businessVerified: true,
    category: "دسر",
    subcategory: "شیرینی",
    price: 35_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 43,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-12-20",
  },

  /* ── فروشگاه پارچه ابریشم گیلان (b002) ─────────────── */
  {
    id: "p005",
    slug: "abrisham-rasht-1m",
    name: "پارچه ابریشم اصل رشت ۱ متر",
    description: "ابریشم تابنده خالص، بافت سنتی گیلان، رنگ‌آمیزی طبیعی",
    businessId: "b002",
    businessName: "فروشگاه پارچه ابریشم گیلان",
    businessVerified: true,
    category: "پارچه و نساجی",
    subcategory: "ابریشم",
    price: 890_000,
    originalPrice: 1_100_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 56,
    coverGradient: "linear-gradient(135deg, #9333EA 0%, #4C1D95 100%)",
    inventoryStatus: "low-stock",
    stockCount: 12,
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-11-01",
  },
  {
    id: "p006",
    slug: "roosari-abrisham",
    name: "روسری ابریشم دست‌بافت",
    description: "روسری خالص ابریشم با نقوش گلدار سنتی گیلان، در ابعاد ۱۴۰×۱۴۰",
    businessId: "b002",
    businessName: "فروشگاه پارچه ابریشم گیلان",
    businessVerified: true,
    category: "پوشاک",
    subcategory: "روسری",
    price: 450_000,
    originalPrice: 580_000,
    discountPercent: 22,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 38,
    coverGradient: "linear-gradient(135deg, #EC4899 0%, #831843 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-10-15",
  },
  {
    id: "p007",
    slug: "charghad-termeh",
    name: "چارقد ترمه گیلان",
    description: "چارقد ترمه‌بافت اصیل، ۱۰۰٪ پشم، طرح سنتی",
    businessId: "b002",
    businessName: "فروشگاه پارچه ابریشم گیلان",
    businessVerified: true,
    category: "پوشاک",
    subcategory: "روسری",
    price: 280_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 29,
    coverGradient: "linear-gradient(135deg, #7C3AED 0%, #2E1065 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-02-10",
  },

  /* ── کافه و شیرینی جنگل (b003) ─────────────────────── */
  {
    id: "p008",
    slug: "cake-jangali",
    name: "کیک جنگلی خانگی ۸ نفره",
    description: "کیک اسفنجی با خامه گردو، گیلاس تازه و شکلات تلخ",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "شیرینی و دسر",
    subcategory: "کیک",
    price: 75_000,
    originalPrice: 95_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 182,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-12-05",
  },
  {
    id: "p009",
    slug: "coffee-ethiopia",
    name: "قهوه اسپشیالتی اتیوپی",
    description: "دانه قهوه اتیوپی Yirgacheffe، رست ملایم، نت‌های توت و گل",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "قهوه",
    subcategory: "دانه قهوه",
    price: 42_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 97,
    coverGradient: "linear-gradient(135deg, #292524 0%, #1C1917 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-11-20",
  },
  {
    id: "p010",
    slug: "shirini-khoshk-gilani",
    name: "شیرینی خشک گیلانی ۵۰۰ گرم",
    description: "شیرینی ناپلئونی، نان برنجی و کماج — بسته هدیه مخصوص",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "شیرینی و دسر",
    subcategory: "شیرینی خشک",
    price: 55_000,
    originalPrice: 68_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 64,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #92400E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-10-10",
  },
  {
    id: "p011",
    slug: "smoothie-jangali",
    name: "اسموتی جنگلی تازه",
    description: "توت فرنگی، موز، اسفناج بچه و شیر بادام — بدون شکر اضافه",
    businessId: "b003",
    businessName: "کافه و شیرینی جنگل",
    businessVerified: true,
    category: "نوشیدنی",
    subcategory: "اسموتی",
    price: 28_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 51,
    coverGradient: "linear-gradient(135deg, #15803D 0%, #052E16 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-03-15",
  },

  /* ── آتلیه عکاسی نور ساری (b004) ─────────────────────── */
  {
    id: "p012",
    slug: "pakij-akasi-portere-1h",
    name: "پکیج عکاسی پرتره ۱ ساعته",
    description: "۳۰ عکس ویرایش‌شده حرفه‌ای، فایل RAW، تحویل ۴۸ ساعته",
    businessId: "b004",
    businessName: "آتلیه عکاسی نور ساری",
    businessVerified: true,
    category: "خدمات عکاسی",
    subcategory: "پرتره",
    price: 450_000,
    originalPrice: 600_000,
    discountPercent: 25,
    currency: "تومان",
    rating: 5.0,
    reviewCount: 43,
    coverGradient: "linear-gradient(135deg, #1860DB 0%, #0A2660 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-09-01",
  },
  {
    id: "p013",
    slug: "pakij-akasi-mahsol-20",
    name: "پکیج عکاسی محصول ۲۰ تصویر",
    description: "عکاسی محصول حرفه‌ای برای فروشگاه آنلاین، بک‌گراند سفید و رنگی",
    businessId: "b004",
    businessName: "آتلیه عکاسی نور ساری",
    businessVerified: true,
    category: "خدمات عکاسی",
    subcategory: "محصول",
    price: 1_200_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 28,
    coverGradient: "linear-gradient(135deg, #0284C7 0%, #0C4A6E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-08-20",
  },
  {
    id: "p014",
    slug: "video-tablighati-30s",
    name: "ویدیوی تبلیغاتی ۳۰ ثانیه‌ای",
    description: "تولید محتوای ویدیویی حرفه‌ای برای اینستاگرام و تلگرام",
    businessId: "b004",
    businessName: "آتلیه عکاسی نور ساری",
    businessVerified: true,
    category: "خدمات تبلیغاتی",
    subcategory: "ویدیو",
    price: 2_800_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 17,
    coverGradient: "linear-gradient(135deg, #6366F1 0%, #312E81 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 6,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-07-15",
  },

  /* ── داروخانه شبانه‌روزی شفا (b005) ─────────────────── */
  {
    id: "p015",
    slug: "vitamin-d3-5000",
    name: "ویتامین D3 5000 واحد ۶۰ عدد",
    description: "ویتامین D3 با جذب بالا، ساخت داروسازی معتبر",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مکمل",
    subcategory: "ویتامین",
    price: 85_000,
    originalPrice: 105_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 93,
    coverGradient: "linear-gradient(135deg, #FBBF24 0%, #D97706 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-11-05",
  },
  {
    id: "p016",
    slug: "omega3-giyahi",
    name: "امگا-۳ گیاهی ۹۰ کپسول",
    description: "روغن بذر کتان و چیا، منبع طبیعی امگا-۳ بدون عطر ماهی",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مکمل",
    subcategory: "روغن",
    price: 145_000,
    currency: "تومان",
    rating: 4.5,
    reviewCount: 47,
    coverGradient: "linear-gradient(135deg, #34D399 0%, #065F46 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-02-20",
  },
  {
    id: "p017",
    slug: "krem-abrasan-soorat",
    name: "کرم آبرسان روز صورت SPF30",
    description: "کرم مرطوب‌کننده با فاکتور ضدآفتاب، مناسب پوست معمولی تا مختلط",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مراقبت پوست",
    subcategory: "کرم روز",
    price: 220_000,
    originalPrice: 290_000,
    discountPercent: 24,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 62,
    coverGradient: "linear-gradient(135deg, #F9A8D4 0%, #9D174D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-10-25",
  },
  {
    id: "p018",
    slug: "mask-shab-retinol",
    name: "ماسک شب رتینول ۰.۳٪",
    description: "ماسک ضدپیری شبانه با رتینول و نیاسینامید، کاهش خطوط ظریف",
    businessId: "b005",
    businessName: "داروخانه شبانه‌روزی شفا",
    businessVerified: true,
    category: "مراقبت پوست",
    subcategory: "ماسک",
    price: 180_000,
    originalPrice: 240_000,
    discountPercent: 25,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 34,
    coverGradient: "linear-gradient(135deg, #FED7AA 0%, #9A3412 100%)",
    inventoryStatus: "low-stock",
    stockCount: 5,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-09-30",
  },

  /* ── صنایع دستی نوروزی (b006) ───────────────────────── */
  {
    id: "p019",
    slug: "safalineh-goldaar",
    name: "سفالینه گل‌دار دست‌ساز",
    description: "کاسه سفالی با نقش گل و مرغ، لعاب آبی کبالت، کوره‌پخت ۱۲۸۰ درجه",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "صنایع دستی",
    subcategory: "سفال",
    price: 320_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 28,
    coverGradient: "linear-gradient(135deg, #B45309 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-08-10",
  },
  {
    id: "p020",
    slug: "tablou-hasir-mazandaran",
    name: "تابلوی حصیربافی مازندران",
    description: "تابلو دیواری حصیربافی دست‌ساز با نقش طبیعت شمال، ابعاد ۶۰×۴۰",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "صنایع دستی",
    subcategory: "حصیربافی",
    price: 550_000,
    originalPrice: 700_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 19,
    coverGradient: "linear-gradient(135deg, #92400E 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-07-20",
  },
  {
    id: "p021",
    slug: "zarf-choobi-naghsh",
    name: "ظرف چوبی منبت‌کاری شده",
    description: "کاسه چوب گردو با کنده‌کاری دستی طرح اسلیمی",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "صنایع دستی",
    subcategory: "چوب",
    price: 185_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 22,
    coverGradient: "linear-gradient(135deg, #78350F 0%, #3B1A0D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-06-15",
  },
  {
    id: "p022",
    slug: "jovaher-nogre-dast-saz",
    name: "گوشواره نقره دست‌ساز گیلان",
    description: "نقره ۹۲۵ با سنگ فیروزه اصل نیشابور، دست‌ساز استاد نوروزی",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "جواهرات",
    subcategory: "گوشواره",
    price: 480_000,
    originalPrice: 620_000,
    discountPercent: 23,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 41,
    coverGradient: "linear-gradient(135deg, #71717A 0%, #18181B 100%)",
    inventoryStatus: "low-stock",
    stockCount: 3,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-05-28",
  },
  {
    id: "p023",
    slug: "dastband-choob-zeytoon",
    name: "دستبند چوب زیتون گیلان",
    description: "دستبند زیتون کوهی با حلقه‌های دستی، هر قطعه منحصربه‌فرد",
    businessId: "b006",
    businessName: "صنایع دستی نوروزی",
    businessVerified: true,
    category: "جواهرات",
    subcategory: "دستبند",
    price: 95_000,
    currency: "تومان",
    rating: 4.6,
    reviewCount: 37,
    coverGradient: "linear-gradient(135deg, #A16207 0%, #3B1A0D 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: true,
    createdAt: "2026-01-30",
  },

  /* ── چای‌خانه سبز لاهیجان (b007) ──────────────────── */
  {
    id: "p024",
    slug: "chai-sabz-organic-200",
    name: "چای سبز ارگانیک لاهیجان ۲۰۰ گرم",
    description: "چای سبز درجه‌یک، بدون سم، چیده‌شده اواخر بهار",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "چای سبز",
    price: 120_000,
    originalPrice: 155_000,
    discountPercent: 23,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 134,
    coverGradient: "linear-gradient(135deg, #15803D 0%, #052E16 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-09-05",
  },
  {
    id: "p025",
    slug: "chai-momtaz-sargol-500",
    name: "چای ممتاز سرگل لاهیجان ۵۰۰ گرم",
    description: "چای قلم ممتاز، بسته‌بندی هدیه، رنگ طلایی و طعم گل",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "چای سیاه",
    price: 320_000,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 87,
    coverGradient: "linear-gradient(135deg, #16A34A 0%, #052E16 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-08-15",
  },
  {
    id: "p026",
    slug: "damnoosh-gol-gaozaban",
    name: "دمنوش گل گاوزبان ۱۰۰ گرم",
    description: "گل گاوزبان خشک‌شده در سایه از مراتع شمال — آرام‌بخش طبیعی",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "دمنوش",
    subcategory: "گیاهی",
    price: 85_000,
    originalPrice: 105_000,
    discountPercent: 19,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 62,
    coverGradient: "linear-gradient(135deg, #7C3AED 0%, #2E1065 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-07-10",
  },
  {
    id: "p027",
    slug: "chai-irani-mokhallat",
    name: "چای مخلوط ایرانی ویژه",
    description: "ترکیب اختصاصی چای قلم، هل، زعفران و گلاب — طعم شرقی",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "چای",
    subcategory: "ترکیبی",
    price: 180_000,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 94,
    coverGradient: "linear-gradient(135deg, #B91C1C 0%, #450A0A 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-06-25",
  },
  {
    id: "p028",
    slug: "baste-hadiyeh-chai",
    name: "بسته هدیه چای لاهیجان پرمیوم",
    description: "جعبه چوبی شامل سرگل، چای سبز، دمنوش و عسل — ایده‌آل هدیه",
    businessId: "b007",
    businessName: "چای‌خانه سبز لاهیجان",
    businessVerified: true,
    category: "هدیه",
    subcategory: "بسته هدیه",
    price: 450_000,
    originalPrice: 580_000,
    discountPercent: 22,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 48,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #78350F 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: true,
    installmentMonths: 3,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-05-10",
  },

  /* ── زنبورداری کوه‌نشین البرز (b008) ─────────────────── */
  {
    id: "p029",
    slug: "asal-goon-alborz-1kg",
    name: "عسل طبیعی گون البرز ۱ کیلو",
    description: "عسل گون خالص، ۱۰۰٪ طبیعی، بدون افزودنی، با شناسنامه زنبورستان",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "عسل",
    subcategory: "عسل طبیعی",
    price: 380_000,
    originalPrice: 490_000,
    discountPercent: 22,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 112,
    coverGradient: "linear-gradient(135deg, #F59E0B 0%, #92400E 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: true,
    isNew: false,
    createdAt: "2025-08-01",
  },
  {
    id: "p030",
    slug: "asal-siyah-dane-500",
    name: "عسل سیاه‌دانه کوهستانی ۵۰۰ گرم",
    description: "عسل با عصاره سیاه‌دانه تقویت‌شده — تقویت سیستم ایمنی",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "عسل",
    subcategory: "عسل دارویی",
    price: 210_000,
    originalPrice: 265_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.8,
    reviewCount: 76,
    coverGradient: "linear-gradient(135deg, #D97706 0%, #451A03 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-07-05",
  },
  {
    id: "p031",
    slug: "moum-zanboor-100g",
    name: "موم زنبور طبیعی ۱۰۰ گرم",
    description: "موم خام طبیعی برای ساخت کرم، شمع و محصولات مراقبتی",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "محصولات زنبور",
    subcategory: "موم",
    price: 85_000,
    currency: "تومان",
    rating: 4.7,
    reviewCount: 34,
    coverGradient: "linear-gradient(135deg, #FBBF24 0%, #B45309 100%)",
    inventoryStatus: "in-stock",
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-06-10",
  },
  {
    id: "p032",
    slug: "propolis-khales-100",
    name: "پروپولیس خالص ۱۰۰ گرم",
    description: "پروپولیس خام با خلوص ۸۰٪+، آنتی‌بیوتیک طبیعی زنبور عسل",
    businessId: "b008",
    businessName: "زنبورداری کوه‌نشین البرز",
    businessVerified: true,
    category: "محصولات زنبور",
    subcategory: "پروپولیس",
    price: 165_000,
    originalPrice: 210_000,
    discountPercent: 21,
    currency: "تومان",
    rating: 4.9,
    reviewCount: 58,
    coverGradient: "linear-gradient(135deg, #A16207 0%, #3B1A0D 100%)",
    inventoryStatus: "low-stock",
    stockCount: 7,
    isInstallmentAvailable: false,
    isFeatured: false,
    isNew: false,
    createdAt: "2025-05-15",
  },
];

/* ── Derived helpers ─────────────────────────────────── */
export const getFeaturedProducts = () =>
  mockProducts.filter(p => p.isFeatured);

export const getDealProducts = () =>
  mockProducts
    .filter(p => p.discountPercent && p.discountPercent >= 19)
    .sort((a, b) => (b.discountPercent ?? 0) - (a.discountPercent ?? 0));

export const getInstallmentProducts = () =>
  mockProducts.filter(p => p.isInstallmentAvailable);

export const getProductsByBusiness = (businessId: string) =>
  mockProducts.filter(p => p.businessId === businessId);

export const getNewProducts = () =>
  mockProducts.filter(p => p.isNew);
